name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          token: ${{ env.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.20.2'

    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Set Git User
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"

    - name: Deploy
      run: npm run deploy
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}