name: Push to gh-pages

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
          token: ${{ env.GITHUB_TOKEN }}

      - name: Push to gh-pages
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git checkout gh-pages
          git rebase main
          git push origin gh-pages
