name: Push to gh-pages

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Push to gh-pages
        run: |
          git checkout gh-pages
          git rebase main
          git push origin gh-pages
