name: Deploy to GitHub pages
on:
  push:
    branches: [ main, gh-pages ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate static VuePress files
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm run build

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
