name: Deploy to GitHub pages
on:
  push:
    branches: [ main, gh-pages ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.20.2'

      - run: npm ci
      - run: npm run build

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
